export const style = {
    overlay: {
        position: "fixed",
        inset: 0,
        zIndex: 50,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "1rem",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        backdropFilter: "blur(4px)",
    },
    modal: {
        width: "100%",
        maxWidth: "28rem",
        backgroundColor: "white",
        borderRadius: "0.5rem",
        boxShadow:
            "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        overflow: "hidden",
    },
    header: {
        padding: "8px",
        paddingLeft: "18px",
        borderBottom: "1px solid #e5e7eb",
    },
    title: {
        fontSize: "1.25rem",
        fontWeight: 600,
        color: "#111827",
        marginTop: "4px"
    },
    subtitle: {
        fontSize: "0.875rem",
        color: "#6b7280",
    },
    search: {
        padding: "1rem",
        borderBottom: "1px solid #e5e7eb",
    },
    searchContainer: {
        position: "relative" as const,
        display: "flex",
        alignItems: "center",
    },
    searchInput: {
        width: "100%",
        padding: "0.5rem 2.5rem 0.5rem 2.5rem",
        border: "1px solid #d1d5db",
        borderRadius: "0.375rem",
        transition: "box-shadow 0.15s ease-in-out, border-color 0.15s ease-in-out",
        fontSize: "14px",
    },
    searchIcon: {
        position: "absolute" as const,
        left: "0.75rem",
        width: "16px",
        height: "16px",
        color: "#6b7280",
        pointerEvents: "none" as const,
    },
    clearButton: {
        position: "absolute" as const,
        right: "0.5rem",
        width: "20px",
        height: "20px",
        border: "none",
        background: "none",
        cursor: "pointer",
        color: "#6b7280",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "50%",
        transition: "background-color 0.15s ease-in-out",
    },
    list: {
        maxHeight: "calc(100vh - 24rem)",
        overflowY: "auto" as const,
    },
    noResults: {
        padding: "2rem",
        textAlign: "center" as const,
        color: "#6b7280",
        fontSize: "0.875rem",
    },
    item: {
        width: "100%",
        padding: "1rem 1.5rem",
        display: "flex",
        alignItems: "flex-start",
        textAlign: "left",
        border: "none",
        borderBottom: "1px solid #e5e7eb",
        transition: "all 0.2s ease-in-out",
        cursor: "pointer",
        backgroundColor: "transparent",
        position: "relative" as const,
    },
    avatar: {
        height: "2.5rem",
        width: "2.5rem",
        flexShrink: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "0.375rem",
        backgroundColor: "rgba(59, 130, 246, 0.1)",
        color: "#2563eb",
        fontWeight: 500,
        transition: "all 0.2s ease-in-out",
    },
    content: {
        marginLeft: "1rem",
        flex: 1,
        minWidth: 0,
        cursor: "pointer",
    },
    itemHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
    },
    itemTitle: {
        fontWeight: 500,
        color: "#111827",
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
    },
    itemDate: {
        marginLeft: "0.5rem",
        fontSize: "0.75rem",
        color: "#6b7280",
    },
    description: {
        fontSize: "0.875rem",
        color: "#6b7280",
        display: "-webkit-box",
        WebkitLineClamp: 2,
        WebkitBoxOrient: "vertical",
        overflow: "hidden",
    },
    members: {
        marginTop: "0.25rem",
        fontSize: "0.75rem",
        color: "#6b7280",
    },
    footer: {
        padding: "1rem",
        borderTop: "1px solid #e5e7eb",
        backgroundColor: "#f9fafb",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    cancelButton: {
        padding: "0.5rem 1rem",
        fontSize: "0.875rem",
        fontWeight: 500,
        color: "#374151",
        backgroundColor: "transparent",
        border: "none",
        borderRadius: "0.375rem",
        cursor: "pointer",
        transition: "all 0.15s ease-in-out",
    },
    createButton: {
        padding: "0.5rem 1rem",
        fontSize: "0.875rem",
        fontWeight: 500,
        color: "#2563eb",
        backgroundColor: "transparent",
        border: "1px solid #2563eb",
        borderRadius: "0.375rem",
        cursor: "pointer",
        transition: "all 0.15s ease-in-out",
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
    },
    editIcon: {
        position: "absolute" as const,
        right: "1rem",
        top: "50%",
        transform: "translateY(-50%)",
        width: "32px",
        height: "32px",
        border: "none",
        background: "none",
        cursor: "pointer",
        color: "#6b7280",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "0.25rem",
        transition: "all 0.15s ease-in-out",
        zIndex: 10,
    },
};